/*Generated by WaveMaker Studio*/

package com.test.highscoredb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Table13 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE13`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`COLUMN2`"})})
public class Table13 implements Serializable {

    private int id;
    private String column2;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "`COLUMN2`", nullable = true, length = 255)
    public String getColumn2() {
        return this.column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table13)) return false;
        final Table13 table13 = (Table13) o;
        return Objects.equals(getId(), table13.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

