/*Generated by WaveMaker Studio*/

package com.test.highscoredb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table12 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE12`")
public class Table12 implements Serializable {

    private int id;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table12)) return false;
        final Table12 table12 = (Table12) o;
        return Objects.equals(getId(), table12.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

